/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 oblject.glb --transform --shadows
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/oblject-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Icosphere001.geometry} material={materials['Material.001']} position={[0.16, 0, 0.28]} scale={0.18} />
    </group>
  )
}

useGLTF.preload('/oblject-transformed.glb')
